import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout";
import WhatsappButton from "@/components/whatsapp-button";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RIOD",
  description: "Generated by fjordstans",
  icons: {
    icon: "/images/riod-white.png",
    apple: "/images/riod-white.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          {children}
          <WhatsappButton/>
        </Layout>
      </body>
    </html>
  );
}
